### ISSUE TITLE
Trait not implemented for ProfilingStructGenerator

### ISSUE THREAD

**Issue by NearlyEnjoyable** [Nercury/gl_generator_profiling_struct-rs#1]
Hello,
The compilation fails on the build script with the following output:

error[E0277]: the trait bound `gl_generator_profiling_struct::ProfilingStructGenerator: gl_generator::generators::Generator` is not satisfied
  --> lib/build.rs:20:10
   |
20 |         .write_bindings(ProfilingStructGenerator, &mut file_gl)
   |          ^^^^^^^^^^^^^^ the trait `gl_generator::generators::Generator` is not implemented for `gl_generator_profiling_struct::ProfilingStructGenerator`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0277`.
error: Could not compile `gl`.

So in short it tells me a trait is not implemented for the generator..

However I can see such implementation in the source:
https://github.com/Nercury/gl_generator_profiling_struct-rs/blob/master/src/lib.rs#L70

The only thing is that it's 
`impl gl_generator::Generator for` not `gl_generator::generators::Generator`
They differ. Could be a typo?

I saw the crate be used in "The openGl tutorial" and wanted to use it myself to have some guidelines.
Did something change? I use the '0.1.2' version where on the tutorial it is '0.1'.
Should I roll back or not use this crate at all because it's just for demonstration?

**Comment by Nercury** [comment]
Hi,

First of all, thank you for report.

I don't know exactly what is going on, and won't have time to investigate
for at least few weeks. But I will look into it once I have time just to
make sure everything keeps compiling.
